### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by iamrocan** [g3th/Netflix-Checker#2] opened 2023-10-20 23:57 UTC
i tried to put into folder my combo called NETFLIX, netflix, Netflix but doesn't work.

**Comment by g3th** [comment] 2023-10-23 17:35
Hi there,

Are you getting an error? Which OS are you using?

The program has a menu with various options. Once you have a valid combo-list named 'netflix' in the program folder, different options will yield different results. For instance, when pressing "Option 1", if you have a USA IP address and the list does not contain any valid USA accounts, the program will simply end.

You can bypass the need for specific IP addresses by running "Option 3," deleting countries from the list with a generic split method and checking every account with your current IP address.

**Comment by iamrocan** [comment] 2023-10-23 17:41
Hi Roberto,

i'm using W11, and i have a error with the name of combo, i have loaded 100K lines in a file named 'netflix' into the main folder, but when i start the program it just say that combo is not found.

**Comment by g3th** [comment] 2023-10-23 18:08
Hi,

How are you running the program? It is suggested that you use ```powershell``` or ```cmd```, and type:

```python3 netflix.py```

I booted up Windows and cannot replicate the issue. The combo-list is in the main program folder, named 'netflix', no capitalization, no file extension (since the program is intended to be used on Debian or a Linux distro).

Try to delete the program folder, running "git clone https://github.com/g3th/Netflix-Checker", then placing the combo-list in the main program folder again.

Try to set up a virtual-machine, i.e. Oracle VM Virtual Box, and running the program from a linux distro instead. Linux distributions are free to use for everyone, unlike Windows OS.

While escape sequences are not displaying properly in Window terminals, the program works fine on Windows 10 for me when running it from powershell.

**Comment by iamrocan** [comment] 2023-10-24 06:39
Hi Roberto, 

I was able to run the program correctly on both Linux and w11, however now I have another problem...

LINUX: It just starts checking the combo, but it doesn't work (it just tries to open a window, I think it's the browser, but it can't open) and it goes into a loop so it doesn't go beyond the first combo.

W11: It is the same error, however here it can  open the chrome window but it does not give results UNLESS before loading the Netflix page you MAXIMIZE the window, then it does give a result.

![Captura de pantalla de 2023-10-24 00-34-12](https://github.com/g3th/Netflix-Checker/assets/60199671/b5001787-db94-4415-a754-f960883048a5)

I add a screenshot of Linux

**Comment by Ijikov** [comment] 2024-01-21 10:16
It works on kali ?

**Comment by g3th** [comment] 2024-02-03 01:25
elements were fixed and the program should be working again. I have only tested it on Debian.
Valid account detection should work, although I don't have a valid Netflix account to test. If you would like to donate, let me know. 
If this isn't updated in a week, I will close it.

**Comment by tokyum** [comment] 2024-02-06 14:08
Traducción al inglés:

I can confirm that it is working effectively
Excellent work
I only needed to add my country to countries.py and modify line 118 " browser = webdriver.Chrome(options = browser_options)"
And it ran perfectly detecting the valid account
THANKS

GRACIAS TOTALES

**Comment by g3th** [comment] 2024-02-06 16:54
At the moment, the program will just work by choosing option 3, then choosing option 1. There isn't really the need to check accounts by country as you can just connect to a VPN and check all accounts that way.

As it's working again, this issue is solved.

**Closed by g3th** 2024-02-06 16:54 UTC
